### ISSUE TITLE
proxy qui bug 

### ISSUE THREAD

**Issue by alphaleadership** [Cyb3rghostx/Proxima#5]
UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:530:11)
    at ServerResponse.header (/home/debian/Proxima/node_modules/express/lib/response.js:794:10)
    at ServerResponse.json (/home/debian/Proxima/node_modules/express/lib/response.js:275:10)
    at ServerResponse.send (/home/debian/Proxima/node_modules/express/lib/response.js:162:21)
    at /home/debian/Proxima/index.js:20:9
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:29431) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)

**Comment by alphaleadership** [comment]
corrigée
